logsBucket: gs://pheneaus-bucket # Replace 'your-logs-bucket' with your actual bucket name

steps:
  # Step 1: Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/aman-project-426023/backend-image:latest', './backend']
    dir: 'backend'

  # Step 2: Push the backend image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/aman-project-426023/backend-image:latest']

  # Step 3: Build the frontend image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/aman-project-426023/frontend-image:latest', './frontend']
    dir: 'frontend'

  # Step 4: Push the frontend image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/aman-project-426023/frontend-image:latest']

  # Step 5: Deploy backend to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', './backend/deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

  # Step 6: Deploy frontend to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', './frontend/deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

  # Step 7: Expose the backend service
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['expose', 'deployment', 'backend-image-deployment', '--type=LoadBalancer', '--name=backend-service', '--port=5000', '--target-port=5000']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

  # Step 8: Expose the frontend service
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['expose', 'deployment', 'frontend-image-deployment', '--type=LoadBalancer', '--name=frontend-service', '--port=80', '--target-port=80']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=$_COMPUTE_ZONE'
      - 'CLOUDSDK_CONTAINER_CLUSTER=$_CLUSTER_NAME'

timeout: '1100s'

# Substitutions for dynamic values
substitutions:
  _COMPUTE_ZONE: 'us-central1-a'
  _CLUSTER_NAME: 'aman'

# Images to be deployed (optional, for tracking purposes)
images:
  - 'gcr.io/aman-project-426023/backend-image:latest'
  - 'gcr.io/aman-project-426023/frontend-image:latest'
